# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.up_json = QtWidgets.QPushButton(self.centralwidget)
        self.up_json.setGeometry(QtCore.QRect(20, 140, 75, 23))
        self.up_json.setObjectName("up_json")
        self.up_csv = QtWidgets.QPushButton(self.centralwidget)
        self.up_csv.setGeometry(QtCore.QRect(160, 140, 75, 23))
        self.up_csv.setObjectName("up_csv")
        self.up_xlsx = QtWidgets.QPushButton(self.centralwidget)
        self.up_xlsx.setGeometry(QtCore.QRect(310, 140, 75, 23))
        self.up_xlsx.setObjectName("up_xlsx")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 240, 371, 321))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(420, 240, 371, 321))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.col_data = QtWidgets.QLineEdit(self.centralwidget)
        self.col_data.setGeometry(QtCore.QRect(20, 180, 371, 20))
        self.col_data.setObjectName("col_data")
        self.import_data = QtWidgets.QPushButton(self.centralwidget)
        self.import_data.setGeometry(QtCore.QRect(20, 200, 371, 23))
        self.import_data.setObjectName("import_data")
        self.exp_json = QtWidgets.QPushButton(self.centralwidget)
        self.exp_json.setGeometry(QtCore.QRect(430, 200, 75, 23))
        self.exp_json.setObjectName("export_JSON")
        self.exp_df = QtWidgets.QPushButton(self.centralwidget)
        self.exp_df.setGeometry(QtCore.QRect(700, 200, 75, 23))
        self.exp_df.setObjectName("export_DataFrame")
        self.exp_csv = QtWidgets.QPushButton(self.centralwidget)
        self.exp_csv.setGeometry(QtCore.QRect(550, 200, 111, 23))
        self.exp_csv.setObjectName("export_CSV")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.up_json.setText(_translate("MainWindow", "Upload JSON"))
        self.up_csv.setText(_translate("MainWindow", "Upload CSV"))
        self.up_xlsx.setText(_translate("MainWindow", "Upload XLSX"))
        self.import_data.setText(_translate("MainWindow", "import Data"))
        self.exp_json.setText(_translate("MainWindow", "export JSON"))
        self.exp_csv.setText(_translate("MainWindow", "export CSV"))
        self.exp_df.setText(_translate("MainWindow", "export DF"))
